name: flow_music
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  hive_ce_flutter: ^2.3.2
  hooks_riverpod: ^3.0.3
  http: ^1.2.1
  riverpod_annotation: ^4.0.0
  intl: ^0.20.2
  audio_service: ^0.18.18
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
