name: flow_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  

  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  firebase_messaging: ^15.0.3
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  google_sign_in_dartio: ^0.3.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_localizations: ^1.12.0
  firebase_ui_oauth: ^1.5.3
  firebase_ui_oauth_apple: ^1.2.21
  firebase_ui_oauth_facebook: ^1.2.21
  firebase_ui_oauth_google: ^1.3.3
  sign_in_with_apple: ^6.1.1
  google_sign_in_ios: ^5.7.6
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
