name: flow_music
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  go_router: ^17.2.3
  hive_ce: ^2.14.0
  hive_flutter: ^1.1.0
  hive_ce_flutter: ^2.3.2
  hooks_riverpod: ^3.0.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0
  package_info_plus: ^10.1.0
  intl: ^0.20.2
  web: ^1.1.1
  audio_service: ^0.18.18
  geolocator: ^14.0.0
  geocoding: ^5.0.0
  share_plus: ^13.1.0
  flutter_map: ^8.3.0
  latlong2: ^0.10.1
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.9
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
