name: flow_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  audioplayers: 6.1.0
  firebase_analytics: 11.3.3
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  freezed_annotation: 2.4.4
  go_router: 14.2.8
  hooks_riverpod: 2.5.2
  http: 1.2.2
  json_annotation: 4.9.0
  riverpod_annotation: 2.3.5
  firebase_messaging: 15.1.3
  youtube_explode_dart: 2.2.2
  path: 1.9.0 
  permission_handler: 11.3.1
  path_provider: 2.1.4
  ffmpeg_kit_flutter_full_gpl: 6.0.3
  flutter_signin_button: 2.0.0
  google_sign_in: 6.2.1
  google_sign_in_dartio: 0.3.0
  firebase_ui_auth: 1.15.0
  cloud_firestore: 5.4.3
  firebase_ui_localizations: 1.12.0
  firebase_ui_oauth: 1.5.3
  firebase_ui_oauth_apple: 1.2.21
  flutter_inappwebview: 6.1.1
  firebase_ui_oauth_google: 1.3.3
  sign_in_with_apple: 6.1.2
  google_sign_in_ios: 5.7.7
  tuple: 2.0.2
  rxdart: 0.28.0
  just_audio: 0.9.40
  cached_network_image: 3.4.1
  youtube_player_flutter: 9.1.0
  audio_session: 0.1.21
  firebase_storage: 12.3.1
  image_picker: 1.1.2
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  riverpod_generator: 2.4.3
  build_runner: 2.4.12
  custom_lint: 0.6.7
  riverpod_lint: 2.3.13
  freezed: 2.5.7
  json_serializable: 6.8.0

flutter:
  uses-material-design: true
