name: flow_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  hive_ce: ^2.14.0
  hive_flutter: ^1.1.0
  hive_ce_flutter: ^2.3.2
  hooks_riverpod: ^3.0.3
  http: ^1.2.1
 
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3
  package_info_plus: 9.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.9
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
