// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAao2eYn-YkPpBaTDCNO5Cc-7-m05J_vYw',
    appId: '1:387031162675:web:99ef321e546e7c18272846',
    messagingSenderId: '387031162675',
    projectId: 'flowmusic-5715a',
    authDomain: 'flowmusic-5715a.firebaseapp.com',
    storageBucket: 'flowmusic-5715a.appspot.com',
    measurementId: 'G-3K7LCVBXFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-72-5HzXCqCGegu_ikErfvS67ntAU6U',
    appId: '1:387031162675:android:b8ca1005cf469d39272846',
    messagingSenderId: '387031162675',
    projectId: 'flowmusic-5715a',
    storageBucket: 'flowmusic-5715a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdJHpAE8OEeCckJTo9E0kLhmdKDHx2_s',
    appId: '1:387031162675:ios:2d714187855c83b9272846',
    messagingSenderId: '387031162675',
    projectId: 'flowmusic-5715a',
    storageBucket: 'flowmusic-5715a.appspot.com',
    iosBundleId: 'com.example.flowMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUdJHpAE8OEeCckJTo9E0kLhmdKDHx2_s',
    appId: '1:387031162675:ios:2d714187855c83b9272846',
    messagingSenderId: '387031162675',
    projectId: 'flowmusic-5715a',
    storageBucket: 'flowmusic-5715a.appspot.com',
    iosBundleId: 'com.example.flowMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAao2eYn-YkPpBaTDCNO5Cc-7-m05J_vYw',
    appId: '1:387031162675:web:cd967b0b6f2a5dcb272846',
    messagingSenderId: '387031162675',
    projectId: 'flowmusic-5715a',
    authDomain: 'flowmusic-5715a.firebaseapp.com',
    storageBucket: 'flowmusic-5715a.appspot.com',
    measurementId: 'G-K25K8B7SSC',
  );
}
